export enum DIA_SEMANA_ENUM {
    SEGUNDA_FEIRA = "SEGUNDA_FEIRA",
    TERCA_FEIRA = "TERCA_FEIRA",
    QUARTA_FEIRA = "QUARTA_FEIRA",
    QUINTA_FEIRA = "QUINTA_FEIRA",
    SEXTA_FEIRA = "SEXTA_FEIRA",
    SABADO = "SABADO",
}